server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_db?serverTimezone=UTC&useSSL=false
    username: rimi
    password: arimi13!
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: /mapper/**/*.xml
